# name: Download Thurston food safety inspection data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Los_Angeles
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'latest'
    - name: Install npm deps
      run: npm install
    - name: Download
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 360
        max_attempts: 3
        command: node counties/thurston.js
    - name: Commit new data
      run: |-
        git config user.name "Mima Mercury"
        git config user.email "hi@mimamercury.com"
        git add -A
        download_date=$(date -u)
        git commit -m "Thurston data: ${download_date} on-behalf-of: @mimamercury hi@mimamercury.com" || exit 0
        git push
